# ディレクトリのツリー表示をできるようにする
[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
  source /Users/matsuokahiroyuki/.config/nvim/plugins/nerdtree.vim
'''

# ページ下部のステータスなどをかっこよく表示
[[plugins]]
repo = 'vim-airline/vim-airline'


[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
  source /Users/matsuokahiroyuki/.config/nvim/plugins/vim-airline-themes.vim
'''

# ノーマルモードのときに gcc でコメントアウト
[[plugins]]
repo = 'tpope/vim-commentary'

# ファイルアイコンを表示
[[plugins]]
repo = 'ryanoasis/vim-devicons'

# ファイル検索ができるようにする
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  source /Users/matsuokahiroyuki/.config/nvim/plugins/denite.vim
'''

# onedarkのカラースキーム
[[plugins]]
repo = 'joshdick/onedark.vim'


#ddc.vimを動かすのにdenoとブリッジする
[[plugins]]
repo = 'vim-denops/denops.vim'

# 自動補完
[[plugins]]
repo = 'Shougo/ddc.vim'
on_event = 'InsertEnter'
depends = ['denops.vim']
hook_add = '''
  source /Users/matsuokahiroyuki/.config/nvim/plugins/ddc.vim
'''

#周辺のワードを取得して候補に出してくれる
[[plugins]]
repo = 'Shougo/ddc-around'

#打った文字から始まるキーワードに絞る
[[plugins]]
repo = 'Shougo/ddc-matcher_head'

#Language Server Protocolを使用するのに必要
[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'

#ddcの並び順を整える
[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

#ddcの補完へのアクセスをカスタマイズできる
[[plugins]]
repo = 'Shougo/pum.vim' 

# ファイル中のgit状態を表示
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  let g:gitgutter_map_keys = 0
  nmap ]c <Plug>(GitGutterNextHunk)
  nmap [c <Plug>(GitGutterPrevHunk)
'''

# phpのフォーマッター
[[plugins]]
repo = 'beanworks/vim-phpfmt'
hook_add = '''
  source /Users/matsuokahiroyuki/.config/nvim/plugins/vim-phpfmt.vim
'''

[[plugins]]
repo = 'yuttie/comfortable-motion.vim'
hook_add = '''
  source /Users/matsuokahiroyuki/.config/nvim/plugins/comfortable-motion.vim
'''


[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
  source /Users/matsuokahiroyuki/.config/nvim/plugins/vim-easymotion.vim
'''

[[plugins]]
repo = 'Xuyuanp/scrollbar.nvim'

